---

- name: "{{ symas_openldap_group }} group"
  ansible.builtin.group:
    name: "{{ symas_openldap_group }}"
    gid: 55
    system: true

- name: "{{ symas_openldap_user }} user"
  ansible.builtin.user:
    name: "{{ symas_openldap_user }}"
    uid: 55
    group: "{{ symas_openldap_group }}"
    comment: OpenLDAP server
    home: /var/symas/openldap-data
    shell: /sbin/nologin
    system: true
