---

- name: OpenLDAP install
  ansible.builtin.package:
    name: "{{ symas_openldap_packages }}"
    state: present

- name: Set owner and group on /var/symas subdirectories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ symas_openldap_user }}"
    group: "{{ symas_openldap_group }}"
  loop:
    - /var/symas/openldap-data
    - /var/symas/run
