---

- name: Uncomment cn=module,cn=config
  ansible.builtin.replace:
    path: "{{ symas_openldap_slapd_ldif_default }}"
    regexp: '^#({{ item }})$'
    replace: '\1'
  loop:
    - 'dn: cn=module,cn=config'
    - 'objectClass: olcModuleList'
    - 'cn: module'
    - "olcModulepath:\t/opt/symas/lib/openldap" # noqa no-tabs
    - "olcModuleload:\tback_mdb.la" # noqa no-tabs

- name: Add schemas
  ansible.builtin.lineinfile:
    path: "{{ symas_openldap_slapd_ldif_default }}"
    line: 'include: file:///opt/symas/etc/openldap/schema/{{ item }}.ldif'
    insertafter: '^include'
  loop: "{{ symas_openldap_schemas }}"

- name: Add block for olcDatabase=config,cn=config
  ansible.builtin.blockinfile:
    path: "{{ symas_openldap_slapd_ldif_default }}"
    block: "{{ '\n' + lookup ( 'file' , 'block-config.ldif' ) + '\n\n' }}"
    insertafter: '^# rootdn can always read and write EVERYTHING!$'

- name: Customize olcDatabase=mdb,cn=config
  ansible.builtin.lineinfile:
    path: "{{ symas_openldap_slapd_ldif_default }}"
    line: "{{ item.attribute }}: {{ item.value }}"
    regexp: '^{{ item.attribute }}: {{ item.regexp | default() }}'
  loop: "{{ symas_openldap_mdb }}"

- name: Attributes to index with eq
  ansible.builtin.lineinfile:
    path: "{{ symas_openldap_slapd_ldif_default }}"
    line: "olcDbIndex: {{ symas_openldap_index_eq | join(',') }} eq"
    insertafter: '^olcDbIndex: objectClass eq'

- name: Attributes to index with eq,sub
  ansible.builtin.lineinfile:
    path: "{{ symas_openldap_slapd_ldif_default }}"
    line: "olcDbIndex: {{ symas_openldap_index_eq_sub | join(',') }} eq,sub"
    insertafter: '^olcDbIndex'
