---

- name: "{{ symas_openldap_slapd_d }} directory"
  ansible.builtin.file:
    path: "{{ symas_openldap_slapd_d }}"
    state: directory
    owner: "{{ symas_openldap_user }}"
    group: "{{ symas_openldap_group }}"
    mode: 0700
    setype: slapd_db_t

# NOTE setype seems to be ignored on distributions not using SELinux so don't
# bother handling this specifically.

- name: slapadd
  ansible.builtin.command:
    cmd: /opt/symas/sbin/slapadd -F "{{ symas_openldap_slapd_d }}" -l "{{ symas_openldap_slapd_ldif_default }}" -n 0
    creates: "{{ symas_openldap_slapd_d }}/cn=config.ldif"

- name: set owner and group on files below {{ symas_openldap_slapd_d }}
  ansible.builtin.file:
    path: "{{ symas_openldap_slapd_d }}"
    owner: "{{ symas_openldap_user }}"
    group: "{{ symas_openldap_group }}"
    recurse: true
